version: '3'
services:

  db:
    container_name: DB_eFacil
    image: mysql:latest
    env_file:
      - ./docker.env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - efacil

volumes:
  db_data:

networks:
  efacil:
    driver: bridge
