version: "3"
services:

  db:
    container_name: DB_eFacil
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
    volumes:
      - db_eFacil:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    restart: unless-stopped
    networks:
      - efacil
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 30s
      retries: 15

volumes:
  db_eFacil:

networks:
  efacil:
    driver: bridge
