### All Customers
GET http://localhost:5000/api/customers

### Single Customer
GET http://localhost:5000/api/customer/:uuid

### Add New Customer
POST http://localhost:5000/api/customer
Content-Type: application/json

{
  "name": "Ryan Luan Vicente Almada",
  "cpf": "88153008307",
  "rg": "7038003518",
  "email": "ryan.luan.almada@edbrasil.net",
  "cell": "9827236445",
  "cep": "65143970",
  "address": "Avenida José da Silva Calvet",
  "number": "306",
  "district": "Centro",
  "city": "Bacabeira",
  "uf": "MA",
  "isActive": true
}

### Update Existing Customer
PATCH http://localhost:5000/api/customer/:uuid
Content-Type: application/json

{
  "name": "Ryan Luan Vicente Almada",
  "cpf": "88153008307",
  "rg": "7038003518",
  "email": "ryan.luan.almada@edbrasil.net",
  "cell": "9827236445",
  "cep": "65143970",
  "address": "Avenida José da Silva Calvet",
  "number": "306",
  "district": "Centro",
  "city": "Bacabeira",
  "uf": "MA",
  "isActive": false
}


### Delete Existing Customer
DELETE http://localhost:5000/api/customer/:uuid
