### All Customers
GET http://localhost:5000/api/v1/customers

### Single Customer
GET http://localhost:5000/api/v1/customer/:uuid

### Add New Customer
POST http://localhost:5000/api/v1/add-customer
Content-Type: application/json

{
  "name": "",
  "registration": ,
  "contactEmail": "",
  "contactNumber": ,
  "cep": ,
  "address": "",
  "number": "",
  "district": "",
  "city": "",
  "uf": "",
  "isActive": true
}

### Update Existing Customer
PATCH http://localhost:5000/api/v1/customer/:uuid
Content-Type: application/json

{
  "name": "",
  "registration": ,
  "contactEmail": "",
  "contactNumber": ,
  "cep": ,
  "address": "",
  "number": "",
  "district": "",
  "city": "",
  "uf": "",
  "isActive": false
}

### Delete Existing Customer
DELETE http://localhost:5000/api/v1/customer/:uuid
