### All Entries
GET http://localhost:5000/api/entries


### Single Entry
GET http://localhost:5000/api/entry/:uuid


### Add New Entry
POST http://localhost:5000/api/entry
Content-Type: application/json

{
  "entryDate": "2022-11-10",
  "total": 5000.00,
  "transport": 0.00,
  "carryingId": "aac027eb-c862-4e16-9a10-802534dd739d",
  "providerId": "0745c735-cd3d-44c1-85b0-5d55adac3455",
  "receiptId": "0bfbe931-219a-4713-982c-2789390f0baa"
}


### Update Existing Entry
PATCH http://localhost:5000/api/entry/:uuid
Content-Type: application/json

{
  "entryDate": "",
  "total": "",
  "transport": "",
  "receipt": "",
  "carryingId": "",
  "providerId": ""
}


### Delete Existing Entry
DELETE http://localhost:5000/api/entry/:uuid
