### All Items
GET http://localhost:5000/api/items


### Single Item
GET http://localhost:5000/api/item/:uuid


### Add New Item
POST http://localhost:5000/api/item
Content-Type: application/json

{
  "unitary": 2500.00,
  "quantity": 1,
  "total": 2500.00,
  "productId": "c267aa42-7a41-4dd6-b816-600f22d9a75f",
  "receiptId": "0bfbe931-219a-4713-982c-2789390f0baa"
},
{
  "unitary": 2500.00,
  "quantity": 1,
  "total": 2500.00,
  "productId": "03fdd7e4-2eb5-4321-8bca-3ef60b309fd6",
  "receiptId": "0bfbe931-219a-4713-982c-2789390f0baa"
}


### Update Existing Item
PATCH http://localhost:5000/api/item/:uuid
Content-Type: application/json

{
  "unitary": "",
  "quantity": "",
  "total": "",
  "productId": "",
  "receiptId": ""
}


### Delete Existing Item
DELETE http://localhost:5000/api/item/:uuid
