### All Movements
GET http://localhost:5000/api/v1/movements

### Single Movement
GET http://localhost:5000/api/v1/movement/uuid

### Add New Movement
POST http://localhost:5000/api/v1/add-movement
Content-Type: application/json

{
  "name": "",
  "registration": ,
  "contactEmail": "",
  "contactNumber": ,
  "cep": ,
  "address": "",
  "number": "",
  "district": "",
  "city": "",
  "uf": "",
  "isActive": true
}

### Update Existing Movement
PATCH http://localhost:5000/api/v1/movement/:uuid
Content-Type: application/json

{
  "name": "",
  "registration": ,
  "contactEmail": "",
  "contactNumber": ,
  "cep": ,
  "address": "",
  "number": "",
  "district": "",
  "city": "",
  "uf": "",
  "isActive": false
}

### Delete Existing Movement
DELETE http://localhost:5000/api/v1/movement/:uuid
