### All Providers
GET http://localhost:5000/api/providers

### Single Provider
GET http://localhost:5000/api/provider/:uuid

### Add New Provider
POST http://localhost:5000/api/provider
Content-Type: application/json

{
  "name": "Henry e Lucas Informática ME",
  "registration": "16958933000126",
  "phone": "1135816411",
  "email": "contabilidade@henryelucasinformaticame.com.br",
  "cep": "09381040",
  "address": "Rua Porto Alegre",
  "number": "781",
  "district": "Jardim Oratório",
  "city": "Mauá",
  "uf": "SP",
  "isActive": true
}

### Update Existing Provider
PATCH http://localhost:5000/api/provider/:uuid
Content-Type: application/json

{
  "name": "",
  "registration": "",
  "phone": "",
  "email": "",
  "cep": "",
  "address": "",
  "number": "",
  "district": "",
  "city": "",
  "uf": "",
  "isActive": false
}


### Delete Existing Provider
DELETE http://localhost:5000/api/provider/:uuid
