### All Receipts
GET http://localhost:5000/api/v1/receipts

### Single Receipt
GET http://localhost:5000/api/v1/receipt/uuid

### Add New Receipt
POST http://localhost:5000/api/v1/add-receipt
Content-Type: application/json

{
  "description": "",
  "manufacturer": "",
  "unitMeasure": "",
  "descriptionUnitMeasure": "",
  "isActive": true
}

### Update Existing Receipt
PATCH http://localhost:5000/api/v1/receipt/:uuid
Content-Type: application/json

{
  "description": "",
  "manufacturer": "",
  "unitMeasure": "",
  "descriptionUnitMeasure": "",
  "isActive": false
}

### Delete Existing Receipt
DELETE http://localhost:5000/api/v1/receipt/:uuid
